# Default configuration for ground truth context evaluation
# Reverses preconditioning using ground truth as context

defaults:
  - _self_
  - data: monash_cached
  - model: moirai_precond_ckpt_no_reverse  # Preconditioned model (no reverse)

# Override fields that are required but not set in the loaded configs
# The actual config structure comes from the model config loaded above

run_name: ???
device: cuda
batch_size: 32
min_batch_size: 1
