# Default configuration for hybrid evaluation
# Combines base model + preconditioned model predictions

defaults:
  - _self_
  - data: monash_cached
  - model@base_model: moirai_lightning_ckpt  # Base model from checkpoint
  - model@precond_model: moirai_precond_ckpt_no_reverse  # Preconditioned model (no reverse)

# Override fields that are required but not set in the loaded configs
# The actual config structure comes from the model configs loaded above

run_name: ???
device: cuda
batch_size: 32
min_batch_size: 1
