_target_: uni2ts.model.moirai2.Moirai2Pretrain
module_kwargs:
  _target_: builtins.dict
  d_model: 384
  d_ff: 1024
  num_layers: 6
  patch_size: 16
  max_seq_len: 512
  attn_dropout_p: 0.0
  dropout_p: 0.0
  scaling: true
  time_precondition_enabled: false
  time_precondition_type: chebyshev
  time_precondition_degree: 5
  time_precondition_stride: 1
  time_precondition_coeffs_init: null
  time_precondition_inverse_enabled: false
  time_precondition_inverse_length: 64
  time_precondition_inverse_stride: 1
  latent_precondition_enabled: false
  latent_precondition_type: chebyshev
  latent_precondition_degree: 5
  latent_precondition_stride: 1
  num_predict_token: 4
prefix_ratio: 0.3
mask_ratio: 0.5
anomaly_zscore_threshold: 0.0
anomaly_variance_ratio_threshold: 4.0
anomaly_variance_min_count: 2
anomaly_resample_attempts: 5
patch_precondition_enabled: false
patch_precondition_type: chebyshev
patch_precondition_degree: 5
patch_precondition_stride: 1
time_precondition_reverse_in_loss: false
time_precondition_inverse_lambda: 0.1
log_on_step: true
max_dim: 1
lr: 1e-3
weight_decay: 1e-1
beta1: 0.9
beta2: 0.98
num_training_steps: ${mul:${trainer.max_epochs},${train_dataloader.num_batches_per_epoch}}
num_warmup_steps: 10_000
